In [20]:
import warnings
warnings.filterwarnings("ignore")
# loading packages
# 1 basic
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

# 1. get the data

In [3]:
train_df=pd.read_csv('train.csv')
store_df=pd.read_csv('store.csv')
test_df=pd.read_csv('test.csv')

# 2. check dataset information

In [6]:

train_df.head()
train_df.info()
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
store_df.info()
print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1017209 entries, 0 to 1017208
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype 
---  ------         --------------    ----- 
 0   Store          1017209 non-null  int64 
 1   DayOfWeek      1017209 non-null  int64 
 2   Date           1017209 non-null  object
 3   Sales          1017209 non-null  int64 
 4   Customers      1017209 non-null  int64 
 5   Open           1017209 non-null  int64 
 6   Promo          1017209 non-null  int64 
 7   StateHoliday   1017209 non-null  object
 8   SchoolHoliday  1017209 non-null  int64 
dtypes: int64(7), object(2)
memory usage: 69.8+ MB
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Store                      1115 non-null   int64  
 1   StoreType               

# 3. try to find the outliers

In [10]:
def check_unique(data):
    for column in data.columns:
        print('{}  unique values quantity: '.format(column),len(data[column].unique()))

## 3.1 check store data set

In [11]:
check_unique(store_df)

Store  unique values quantity:  1115
StoreType  unique values quantity:  4
Assortment  unique values quantity:  3
CompetitionDistance  unique values quantity:  655
CompetitionOpenSinceMonth  unique values quantity:  13
CompetitionOpenSinceYear  unique values quantity:  24
Promo2  unique values quantity:  2
Promo2SinceWeek  unique values quantity:  25
Promo2SinceYear  unique values quantity:  8
PromoInterval  unique values quantity:  4


In [9]:
np.sort(store_df['CompetitionOpenSinceMonth'].unique())

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., nan])

In [12]:
np.sort(store_df['CompetitionOpenSinceYear'].unique())

array([1900., 1961., 1990., 1994., 1995., 1998., 1999., 2000., 2001.,
       2002., 2003., 2004., 2005., 2006., 2007., 2008., 2009., 2010.,
       2011., 2012., 2013., 2014., 2015.,   nan])

## 3.2 check train data set

In [15]:
check_unique(train_df)

Store  unique values quantity:  1115
DayOfWeek  unique values quantity:  7
Date  unique values quantity:  942
Sales  unique values quantity:  21734
Customers  unique values quantity:  4086
Open  unique values quantity:  2
Promo  unique values quantity:  2
StateHoliday  unique values quantity:  5
SchoolHoliday  unique values quantity:  2


In [18]:
train_df['StateHoliday'].unique()
train_df['StateHoliday']=train_df.StateHoliday.map({'0':'none',0:'none','a':'public holiday','b':'Easter','c':'Christmas'})
train_df['StateHoliday'].unique()

array(['none', 'public holiday', 'Easter', 'Christmas'], dtype=object)

## 3.2 check test data set

In [14]:
check_unique(test_df)

Id  unique values quantity:  41088
Store  unique values quantity:  856
DayOfWeek  unique values quantity:  7
Date  unique values quantity:  48
Open  unique values quantity:  3
Promo  unique values quantity:  2
StateHoliday  unique values quantity:  2
SchoolHoliday  unique values quantity:  2


In [19]:
test_df['StateHoliday'].unique()

array(['0', 'a'], dtype=object)

In [21]:
test_df['Open'].unique()

array([ 1., nan,  0.])